version: "~> 1.0"
sudo: true
dist: bionic
language: node_js
node_js:
  - 13
  - 12
  - 11
branches:
  only:
    - master
    - dev
cache: yarn
services:
  - docker
before_install:
  - docker-compose -f docker-compose.test.yml up -d
install:
  - yarn install
  - yarn global add codecov
  - yarn global add nyc
script:
  - yarn lint
  - yarn test
  - codecov
deploy:
  edge: true
  provider: npm
  email: "paulosales@gmail.com"
  api_key: "$NPM_API_KEY"
  on:
    branch: master
    repo: paulosales/crimemap-sync-cli
