version: ~> 1.0

sudo: true
dist: bionic

language: node_js

branches:
  only:
    - master
    - dev

env:
  - CODECOV_TOKEN=0e354bd2-c9a3-471f-a187-521a7ac7d713

cache: yarn

install:
  - yarn install
  - yarn global add codecov --prefix /usr/local

jobs:
  include:
    - stage: lint
      node_js: '13'
      script:
        - yarn lint
    - stage: test
      node_js: '13'
      sudo: required
      script:
        - yarn test
    - stage: codecov
      node_js: '13'
      sudo: required
      script:
        - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
        - codecov

stages:
  - lint
  - test
  - codecov
