version: ~> 1.0

sudo: true
dist: bionic

language: node_js
node_js:
  - 13
  - 12
  - 11

branches:
  only:
    - master
    - dev

env:
  - CODECOV_TOKEN=0e354bd2-c9a3-471f-a187-521a7ac7d713

cache: yarn

services:
  - docker

before_install:
  - docker-compose -f docker-compose.test.yml up

install:
  - yarn install
  - yarn global add codecov
  - yarn global add nyc

script:
  - yarn lint
  - yarn test
  - codecov
