version: "3.6"

volumes:
  database_files:
  database_config:

networks:
  network_api:
    driver: bridge

services:
  database:
    image: mongo:4.2
    container_name: database
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopwd
      - MONGO_INITDB_USERNAME=crimemap
      - MONGO_INITDB_PASSWORD=crimemappwd
      - MONGO_INITDB_DATABASE=crimemapdb
      - MONGO_INITDB_TEST_DATABASE=crimemapdb_test
    volumes:
      - database_files:/data/db
      - database_config:/data/configdb
      - ./scripts/mongo:/docker-entrypoint-initdb.d
    networks:
      - network_api
    expose:
      - "27017"
  api:
    image: prsales/crimemap-sync-api:latest
    container_name: api
    environment:
      - NODE_ENV=testing
    links: 
      - database
    depends_on:
      - database
    networks:
      - network_api
    ports:
      - "4000:4000"
